// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a session-level advisory lock, which a transaction
    // pooler (Neon's -pooler host, PgBouncer) cannot hold: each statement may
    // land on a different backend, so `migrate deploy` fails with P1002.
    // Prefer the direct connection here. This file only configures the Prisma
    // CLI — the runtime client keeps using the pooled DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
